services:
  db:
    image: mariadb:latest
    container_name: wp_db
    restart: always
    environment:
      MARIADB_DATABASE: wordpress
      MARIADB_USER: wpuser
      MARIADB_PASSWORD: wp_pass
      MARIADB_ROOT_PASSWORD: root_pass
    volumes:
      - wpdata:/var/lib/mysql

  php:
    image: wordpress:php8.2-fpm
    container_name: wp_php
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wp_pass
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wpdata:/var/www/html
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: wp_nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - wpdata:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

volumes:
  wpdata:
